name: sono
description: SONO - Modern Music Player by SKYDIVEX
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  audio_session: ^0.1.18
  on_audio_query: 2.9.0
  permission_handler: ^11.3.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  rxdart: ^0.27.7
  equatable: ^2.0.5
  path: ^1.9.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true