name: Build SONO APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate and Print Keystore
        run: |
          keytool -genkey -v \
            -keystore /tmp/sono.keystore \
            -alias sono \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass sono2026 \
            -keypass sono2026 \
            -dname "CN=SKYDIVEX, OU=SONO, O=SKYDIVEX, L=TR, S=TR, C=TR"
          echo "KEYSTORE_BASE64_START"
          base64 -w 0 /tmp/sono.keystore
          echo ""
          echo "KEYSTORE_BASE64_END"
