2026-06-06T20:29:38.3253521Z ##[group]Run softprops/action-gh-release@v2
with:
  tag_name: v1.0.21
  name: SONO v1.0.21
  files: build/app/outputs/flutter-apk/app-release.apk
  overwrite_files: true
  token: ***
env:
  JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.19-10/x64
  JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.19-10/x64
  FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.22.0-x64/flutter
  PUB_CACHE: /home/runner/.pub-cache
  GITHUB_TOKEN: ***
🤔 Pattern 'build/app/outputs/flutter-apk/app-release.apk' does not match any files.
👩‍🏭 Creating new GitHub release for tag v1.0.21...
⚠️ GitHub release failed with status: 403
{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/releases/releases#create-a-release","status":"403"}
Skip retry — your GitHub token/PAT does not have the required permission to create a release
⚠️ Unexpected error fetching GitHub release for tag refs/heads/main: HttpError: Resource not accessible by integration - https://docs.github.com/rest/releases/releases#create-a-release
Resource not accessible by integration - https://docs.github.com/rest/releases/releases#create-a-release